eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9000/eureka
hibernate:
    format_sql: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
spring:
    application:
        name: customerms
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: scooby
        url: jdbc:mysql://localhost:3306/customermsdb
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
